language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lyugaloki/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lyugaloki/docker-react npm run test